### ISSUE TITLE
cannot bind a mongo-db service following instructions

### ISSUE THREAD

**Issue by vladp** [cloudfoundry-samples/vertx-vtoons#2]
Running VMC on Linux x64 fedora 17, and using micro cloud foundry 123

During vmc push vertex-vtoons
## experiencing the following failure below

Create services for application?> y

1: mongodb 2.0
2: mysql 5.1
3: postgresql 9.0
4: rabbitmq 2.4
5: redis 2.2
What kind?> 1

Name?> mongodb-vtoons

Creating service mongodb-vtoons... OK
NoMethodError: undefined method `name' for nil:NilClass
For more information, see ~/.vmc/crash

---

Time of crash:
  2012-12-27 00:41:17 -0500

NoMethodError: undefined method `name' for nil:NilClass

vmc-0.4.7/lib/vmc/cli/service/bind.rb:18:in `bind_service'
mothership-0.3.5/lib/mothership/base.rb:61:in`run'
mothership-0.3.5/lib/mothership/command.rb:68:in `block in invoke'
mothership-0.3.5/lib/mothership/command.rb:82:in`instance_exec'
mothership-0.3.5/lib/mothership/command.rb:82:in `invoke'
mothership-0.3.5/lib/mothership/base.rb:68:in`invoke'
vmc-0.4.7/lib/vmc/cli/service/create.rb:98:in `create_service'
mothership-0.3.5/lib/mothership/base.rb:61:in`run'
mothership-0.3.5/lib/mothership/command.rb:68:in `block in invoke'
mothership-0.3.5/lib/mothership/command.rb:82:in`instance_exec'
mothership-0.3.5/lib/mothership/command.rb:82:in `invoke'
mothership-0.3.5/lib/mothership/base.rb:68:in`invoke'
vmc-0.4.7/lib/vmc/cli/app/push/create.rb:92:in `create_services'
vmc-0.4.7/lib/vmc/cli/app/push.rb:97:in`setup_new_app'
vmc-0.4.7/lib/vmc/cli/app/push.rb:82:in `push'
mothership-0.3.5/lib/mothership/base.rb:61:in`run'

**Comment by vladp** [comment]
reply to my own question, probably should not have asked...
Even though I still have trouble deploying vert.x vtoons sample, I have passed at least the service bind problems (to mongodb).
Issue was in miss match of the libraries/modules (which includes cloudfoundry 0.8.1 library)

Vtoons example was written before vert.x module repository so instructions in vtoons did not include
Adding mongo and cloudfundry modules  
cd <your app>/vert.x

 ./bin/vertx install org.cloudfoundry.cloudfoundry-runtime-v0.8.1
 ./bin/vertx install vertx.mongo-persistor-v1.2

v@clin32a:~/devel/other/vertx-vtoons$ vmc bind-service
1: vertx-sal1ui1
2: env
3: vertx-vtoons
Which application?> 3

1: mongodb-tst1
2: mongodb_v1
3: mongodb-vtoons
Which service instance?> 3

Binding mongodb-vtoons to vertx-vtoons... OK

v@clin32a:~/devel/other/vertx-vtoons$ vmc start vertx-vtoons
Starting vertx-vtoons... OK
Checking vertx-vtoons... GAVE UP
Application failed to start.

(I do not have local (non-MCF) environment to debug the sample in, so will see if MCF logs can give some guidance)

thx
